import { Metadata, ResolvingMetadata } from "next";
import { getSharedConfig } from "@/lib/actions/shared";
import { notFound } from "next/navigation";
import Link from "next/link";
import CodeViewer from "@/components/wizard/CodeViewer";
import { PROJECT_TEMPLATES } from "@/lib/engine/templates";
import Navbar from "@/components/Navbar";

interface Props {
  params: Promise<{ slug: string }>;
}

export async function generateMetadata(
  { params }: Props,
  parent: ResolvingMetadata
): Promise<Metadata> {
  const { slug } = await params;
  const config = await getSharedConfig(slug);

  if (!config) return { title: "Config Not Found | Initra" };

  return {
    title: `${config.projectName} | Shared Agent Config`,
    description: `A customized ${config.templateSlug} agent configuration generated with Initra. Review the rules and stack options.`,
    openGraph: {
      title: `${config.projectName} - Initra Config`,
      description: `Generated by ${config.profiles?.username || "an Initra user"}`,
      type: "website",
    },
  };
}

export default async function SharedConfigPage({ params }: Props) {
  const { slug } = await params;
  const shared = await getSharedConfig(slug);

  if (!shared) notFound();

  const template = PROJECT_TEMPLATES.find(t => t.slug === shared.templateSlug);
  
  // We'll regenerate the preview files based on the shared config
  // (In a more complex app, we might store the generated files directly)
  // For now, we'll show a summary and the core configuration.

  return (
    <>
      <Navbar />
      <div className="wizard-container py-12">
        <div className="container">
          <div className="review-layout">
            <div className="review-content">
              <h1 className="text-3xl font-extrabold mb-2" style={{ color: "var(--text-primary)" }}>
                {shared.projectName}
              </h1>
              <p className="text-secondary mb-8">
                Shared by <strong>{shared.profiles?.username || "Anonymous"}</strong> • {new Date(shared.created_at).toLocaleDateString()}
              </p>

              <div className="card-glass p-8 mb-8">
                <div style={{ display: "flex", alignItems: "center", gap: "1rem", marginBottom: "1.5rem" }}>
                  <span style={{ fontSize: "2.5rem" }}>{template?.icon}</span>
                  <div>
                    <h2 style={{ fontSize: "1.25rem", color: "var(--text-primary)" }}>{template?.name} Template</h2>
                    <p style={{ fontSize: "0.85rem", color: "var(--text-secondary)" }}>Configured for {shared.config.stackConfig.language}</p>
                  </div>
                </div>

                <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
                  <div className="p-4 rounded-lg bg-white/5 border border-white/10">
                    <span className="block text-xs uppercase text-muted mb-1">Packages</span>
                    <span className="font-semibold">{shared.config.selectedPackages.length}</span>
                  </div>
                  <div className="p-4 rounded-lg bg-white/5 border border-white/10">
                    <span className="block text-xs uppercase text-muted mb-1">Services</span>
                    <span className="font-semibold">{shared.config.selectedServices.length}</span>
                  </div>
                  <div className="p-4 rounded-lg bg-white/5 border border-white/10">
                    <span className="block text-xs uppercase text-muted mb-1">Database</span>
                    <span className="font-semibold">{shared.config.stackConfig.database || "None"}</span>
                  </div>
                  <div className="p-4 rounded-lg bg-white/5 border border-white/10">
                    <span className="block text-xs uppercase text-muted mb-1">Auth</span>
                    <span className="font-semibold">{shared.config.stackConfig.auth || "None"}</span>
                  </div>
                </div>

                <div style={{ padding: "1.5rem", background: "rgba(0,255,255,0.03)", borderRadius: "12px", border: "1px dashed rgba(0,255,255,0.1)" }}>
                   <p className="text-sm italic text-secondary text-center">
                     "This configuration is ready for use with Cursor or Windsurf. Start building with this stack in seconds."
                   </p>
                </div>
              </div>

              <div className="flex gap-4">
                <Link href="/wizard" className="btn btn-primary px-8">
                  🪄 Use This Stack
                </Link>
                <Link href="/community" className="btn btn-secondary px-8">
                  🌍 Explore More
                </Link>
              </div>
            </div>

            <div className="review-sidebar">
               <div className="card-glass p-6">
                 <h3 className="text-sm font-bold uppercase tracking-wider text-muted mb-4">Stack Details</h3>
                 <div className="space-y-4">
                    {Object.entries(shared.config.stackConfig).map(([key, value]) => (
                      <div key={key} className="flex justify-between items-center text-sm">
                        <span className="text-muted capitalize">{key.replace(/([A-Z])/g, ' $1')}</span>
                        <span className="font-mono text-cyan-400">{String(value)}</span>
                      </div>
                    ))}
                 </div>
               </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
