import { Metadata, ResolvingMetadata } from "next";
import { getSharedConfig } from "@/lib/actions/shared";
import { notFound } from "next/navigation";
import Link from "next/link";
import CodeViewer from "@/components/wizard/CodeViewer";
import { PROJECT_TEMPLATES } from "@/lib/engine/templates";
import Navbar from "@/components/Navbar";

interface Props {
  params: Promise<{ slug: string }>;
}

export async function generateMetadata(
  { params }: Props,
  parent: ResolvingMetadata
): Promise<Metadata> {
  const { slug } = await params;
  const config = await getSharedConfig(slug);

  if (!config) return { title: "Config Not Found | Initra" };

  return {
    title: `${config.projectName} | Shared Agent Config`,
    description: `A customized ${config.templateSlug} agent configuration generated with Initra. Review the rules and stack options.`,
    openGraph: {
      title: `${config.projectName} - Initra Config`,
      description: `Generated by ${config.profiles?.display_name || "an Initra user"}`,
      type: "website",
    },
  };
}

export default async function SharedConfigPage({ params }: Props) {
  const { slug } = await params;
  const shared = await getSharedConfig(slug);

  if (!shared) notFound();

  const template = PROJECT_TEMPLATES.find(t => t.slug === shared.templateSlug);
  
  // We'll regenerate the preview files based on the shared config
  // (In a more complex app, we might store the generated files directly)
  // For now, we'll show a summary and the core configuration.

  return (
    <>
      <Navbar />
      <div className="wizard-container py-12">
        <div className="container">
          <div className="review-layout">
            <div className="review-content">
              <h1 className="text-3xl font-extrabold mb-2" style={{ color: "var(--text-primary)" }}>
                {shared.projectName}
              </h1>
              <p className="text-secondary mb-8">
                Shared by <strong>{shared.profiles?.display_name || "Anonymous"}</strong> • {new Date(shared.created_at).toLocaleDateString()}
              </p>

              <div className="card p-8 mb-8" style={{ background: "var(--bg-card)", borderColor: "var(--border-medium)" }}>
                <div style={{ display: "flex", alignItems: "center", gap: "1.25rem", marginBottom: "2rem" }}>
                  <span style={{ fontSize: "3rem" }}>{template?.icon}</span>
                  <div>
                    <h2 style={{ fontSize: "1.5rem", color: "var(--text-primary)", fontWeight: 700 }}>{template?.name}</h2>
                    <p style={{ fontSize: "0.9rem", color: "var(--text-accent)", fontWeight: 500 }}>Configured for {shared.config.stackConfig.language}</p>
                  </div>
                </div>

                <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))", gap: "1rem", marginBottom: "2rem" }}>
                  <div style={{ padding: "1rem", borderRadius: "12px", background: "var(--bg-tertiary)", border: "1px solid var(--border-subtle)" }}>
                    <span style={{ display: "block", fontSize: "0.7rem", textTransform: "uppercase", color: "var(--text-muted)", marginBottom: "0.25rem", fontWeight: 700 }}>Packages</span>
                    <span style={{ fontSize: "1.1rem", fontWeight: 700, color: "var(--text-primary)" }}>{shared.config.selectedPackages.length}</span>
                  </div>
                  <div style={{ padding: "1rem", borderRadius: "12px", background: "var(--bg-tertiary)", border: "1px solid var(--border-subtle)" }}>
                    <span style={{ display: "block", fontSize: "0.7rem", textTransform: "uppercase", color: "var(--text-muted)", marginBottom: "0.25rem", fontWeight: 700 }}>Services</span>
                    <span style={{ fontSize: "1.1rem", fontWeight: 700, color: "var(--text-primary)" }}>{shared.config.selectedServices.length}</span>
                  </div>
                  <div style={{ padding: "1rem", borderRadius: "12px", background: "var(--bg-tertiary)", border: "1px solid var(--border-subtle)" }}>
                    <span style={{ display: "block", fontSize: "0.7rem", textTransform: "uppercase", color: "var(--text-muted)", marginBottom: "0.25rem", fontWeight: 700 }}>Database</span>
                    <span style={{ fontSize: "1.1rem", fontWeight: 700, color: "var(--text-primary)" }}>{shared.config.stackConfig.database || "None"}</span>
                  </div>
                  <div style={{ padding: "1rem", borderRadius: "12px", background: "var(--bg-tertiary)", border: "1px solid var(--border-subtle)" }}>
                    <span style={{ display: "block", fontSize: "0.7rem", textTransform: "uppercase", color: "var(--text-muted)", marginBottom: "0.25rem", fontWeight: 700 }}>Auth</span>
                    <span style={{ fontSize: "1.1rem", fontWeight: 700, color: "var(--text-primary)" }}>{shared.config.stackConfig.auth || "None"}</span>
                  </div>
                </div>

                <div style={{ padding: "1.5rem", background: "var(--bg-primary)", borderRadius: "12px", border: "1px dashed var(--border-accent)" }}>
                   <p style={{ fontSize: "0.9rem", fontStyle: "italic", color: "var(--text-secondary)", textAlign: "center", margin: 0 }}>
                     "This configuration is ready for use with Cursor or Windsurf. Start building with this stack in seconds."
                   </p>
                </div>
              </div>

              <div style={{ display: "flex", gap: "1rem" }}>
                <Link href="/wizard" className="btn btn-primary" style={{ padding: "0.75rem 2rem" }}>
                  🪄 Use This Stack
                </Link>
                <Link href="/community" className="btn btn-secondary" style={{ padding: "0.75rem 2rem" }}>
                  🌍 Explore More
                </Link>
              </div>
            </div>

            <div className="review-sidebar">
               <div className="card p-6" style={{ background: "var(--bg-secondary)", borderColor: "var(--border-medium)" }}>
                 <h3 style={{ fontSize: "0.75rem", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.05em", color: "var(--text-muted)", marginBottom: "1.5rem" }}>Stack Details</h3>
                 <div style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>
                    {Object.entries(shared.config.stackConfig).map(([key, value]) => (
                      <div key={key} style={{ display: "flex", justifyContent: "space-between", alignItems: "center", fontSize: "0.85rem", borderBottom: "1px solid var(--border-subtle)", paddingBottom: "0.5rem" }}>
                        <span style={{ color: "var(--text-muted)", textTransform: "capitalize" }}>{key.replace(/([A-Z])/g, ' $1')}</span>
                        <span style={{ fontWeight: 600, color: "var(--accent-secondary-light)", fontFamily: "var(--font-mono)" }}>{String(value)}</span>
                      </div>
                    ))}
                 </div>
               </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
