/**
 * Initra — ADR Generator
 * Automatically generates Architectural Decision Records based on audit findings.
 */

import { AuditCheck, GeneratedFile } from "./types";

/**
 * Creates an ADR file content for a specific audit repair.
 */
export function generateAuditADR(check: AuditCheck, framework: string): GeneratedFile {
  const adrNumber = Math.floor(Math.random() * 900) + 100; // Simplified ADR indexing
  const date = new Date().toISOString().split('T')[0];
  
  const content = `# ADR-${adrNumber}: Quality Improvement — ${check.title}

*   **Status**: Accepted
*   **Date**: ${date}
*   **Context**: Quality audit identified a ${check.status} regarding ${check.category}.
*   **Decision**: Applied autonomous repair to address the following issue: ${check.message}
*   **Consequences**:
    *   Improved project health score.
    *   Enhanced compliance with ${check.category} best practices.
    *   Automated injection of ${framework}-optimized architectural patterns.

---
*Generated by Initra Autonomous Quality Auditor*
`;

  return {
    ideTarget: 'universal',
    filename: `ADR-${adrNumber}-Quality-Fix.md`,
    filePath: `docs/adr/ADR-${adrNumber}-Quality-Fix.md`,
    content
  };
}
