// =============================================
// Initra — Agent Team Blueprint Generator
// Generates typed agent role definitions for IDEs
// that support subagents, skills, and team configs.
// =============================================

import { IDETarget, GeneratedFile, TemplateVariables } from './types';

/** Agent role archetypes available for blueprint generation */
export type AgentRole = 'architect' | 'coder' | 'tester' | 'reviewer' | 'researcher';

/** Per-role metadata used in blueprint templates */
interface AgentRoleMeta {
  role: AgentRole;
  title: string;
  icon: string;
  description: string;
  capabilities: string[];
  guardrails: string[];
}

/** Registry of standard agent role definitions */
const AGENT_ROLES: AgentRoleMeta[] = [
  {
    role: 'architect',
    title: 'Architect',
    icon: '🏗️',
    description: 'System design, API contracts, schema decisions, and documentation.',
    capabilities: ['system-design', 'api-design', 'schema-decisions', 'documentation'],
    guardrails: [
      'Never modify migration files without confirmation.',
      'Never commit secrets or credentials.',
      'Always validate schema changes against existing data.',
    ],
  },
  {
    role: 'coder',
    title: 'Coder',
    icon: '💻',
    description: 'Implementation, feature building, refactoring, and debugging.',
    capabilities: ['code-generation', 'refactoring', 'debugging', 'feature-building'],
    guardrails: [
      'Always read a file before editing it.',
      'Prefer editing existing files to creating new ones.',
      'Keep files under 500 lines.',
      'Use the project CSS design system — no inline styles.',
    ],
  },
  {
    role: 'tester',
    title: 'Tester',
    icon: '🧪',
    description: 'Test writing, coverage analysis, edge case discovery.',
    capabilities: ['unit-testing', 'integration-testing', 'coverage-analysis', 'edge-cases'],
    guardrails: [
      'Never delete failing tests — fix them instead.',
      'Always include edge cases and error paths.',
      'Test files must be co-located or in __tests__/ directories.',
    ],
  },
  {
    role: 'reviewer',
    title: 'Reviewer',
    icon: '🔍',
    description: 'Code quality, security review, best practices enforcement.',
    capabilities: ['code-review', 'security-audit', 'best-practices', 'performance-review'],
    guardrails: [
      'Flag any use of `any` type in TypeScript.',
      'Flag SQL injection risks (non-parameterized queries).',
      'Flag client-side exposure of secrets or service keys.',
    ],
  },
  {
    role: 'researcher',
    title: 'Researcher',
    icon: '🔬',
    description: 'Codebase analysis, dependency audit, documentation.',
    capabilities: ['codebase-exploration', 'dependency-audit', 'documentation', 'pattern-discovery'],
    guardrails: [
      'Read-only operations — do not modify files.',
      'Report findings in structured format.',
      'Cross-reference with official documentation.',
    ],
  },
];

// ── IDE-Specific Blueprint Generators ──────────────

/**
 * Main entry point: generate agent team blueprint files for a given IDE.
 * Only produces output for IDEs that support subagent/team configurations.
 */
export function generateAgentBlueprints(
  ideTarget: IDETarget,
  variables: TemplateVariables
): GeneratedFile[] {
  switch (ideTarget) {
    case 'claude-code':
      return generateClaudeCodeBlueprints(variables);
    case 'cursor':
      return generateCursorBlueprints(variables);
    case 'codex':
      return generateCodexBlueprints(variables);
    case 'junie':
      return generateJunieBlueprints(variables);
    case 'factory':
      return generateFactoryBlueprints(variables);
    case 'windsurf':
      return generateWindsurfBlueprints(variables);
    case 'copilot':
      return generateCopilotBlueprints(variables);
    default:
      // IDEs without subagent support get no blueprints
      return [];
  }
}

// ── Claude Code: YAML agent definitions ─────────

function generateClaudeCodeBlueprints(vars: TemplateVariables): GeneratedFile[] {
  return AGENT_ROLES.map((agent) => {
    const content = `# ${agent.title} agent configuration
# Generated by Initra for ${vars.projectName}
type: ${agent.role}
capabilities:
${agent.capabilities.map((c) => `  - ${c}`).join('\n')}
optimizations:
  - context-caching
  - memory-persistence
project:
  name: ${vars.projectName}
  framework: ${vars.framework}
  language: ${vars.language}
`;

    return {
      ideTarget: 'claude-code' as IDETarget,
      filename: `${agent.role}.yaml`,
      filePath: `.claude/agents/${agent.role}.yaml`,
      content,
    };
  });
}

// ── Cursor: MDC subagent definitions ────────────

function generateCursorBlueprints(vars: TemplateVariables): GeneratedFile[] {
  return AGENT_ROLES.map((agent) => {
    const content = `---
name: ${agent.role}
description: "${agent.description}"
model: inherit
---
# ${agent.icon} ${agent.title} Agent — ${vars.projectName}

> ${agent.description}

## Tech Context
- **Framework**: ${vars.framework}
- **Language**: ${String(vars.languageLabel || vars.language)}
${vars.database ? `- **Database**: ${vars.database}` : ''}
${vars.testing ? `- **Testing**: ${vars.testing}` : ''}
- **Orchestration**: ${vars.orchestrationMode} (${vars.swarmTopology} topology)
- **Methodology**: ${vars.developmentMethodology === 'sparc' ? 'SPARC Protocol' : 'Standard'}

## Capabilities
${agent.capabilities.map((c) => `- ${c}`).join('\n')}

## Guardrails
${agent.guardrails.map((g) => `- ${g}`).join('\n')}
`;

    return {
      ideTarget: 'cursor' as IDETarget,
      filename: `${agent.role}.mdc`,
      filePath: `.cursor/agents/${agent.role}.mdc`,
      content,
    };
  });
}

// ── Codex: TOML agent definitions ───────────────

function generateCodexBlueprints(vars: TemplateVariables): GeneratedFile[] {
  return AGENT_ROLES.map((agent) => {
    const toolMap: Record<AgentRole, string[]> = {
      architect: ['read', 'write', 'edit', 'glob', 'grep'],
      coder: ['read', 'write', 'edit', 'bash', 'glob', 'grep'],
      tester: ['read', 'write', 'edit', 'bash', 'grep'],
      reviewer: ['read', 'glob', 'grep'],
      researcher: ['read', 'glob', 'grep', 'web_search'],
    };

    const modelMap: Record<AgentRole, string> = {
      architect: 'inherit',
      coder: 'fast',
      tester: 'fast',
      reviewer: 'inherit',
      researcher: 'inherit',
    };

    const tools = toolMap[agent.role] || ['read', 'glob', 'grep'];
    const model = modelMap[agent.role] || 'inherit';

    const guardrailLines = agent.guardrails
      .map((g) => g.replace(/"/g, '\\"'))
      .join('\\n');

    const content = `# ${agent.title} agent configuration
# Generated by Initra for ${vars.projectName}

name = "${agent.role}"
description = "${agent.description}"

developer_instructions = """
You are a ${agent.title} for the ${vars.projectName} project.
Framework: ${vars.framework} | Language: ${String(vars.languageLabel || vars.language)}${vars.database ? ` | Database: ${vars.database}` : ''}

Guardrails:
${agent.guardrails.map((g) => `- ${g}`).join('\n')}
"""

[tools]
enabled = [${tools.map((t) => `"${t}"`).join(', ')}]

[model]
preference = "${model}"
`;

    return {
      ideTarget: 'codex' as IDETarget,
      filename: `${agent.role}.toml`,
      filePath: `.codex/agents/${agent.role}.toml`,
      content,
    };
  });
}

// ── Junie: Markdown subagent definitions ────────

function generateJunieBlueprints(vars: TemplateVariables): GeneratedFile[] {
  const toolGroupMap: Record<AgentRole, string[]> = {
    architect: ['Read', 'Write', 'Edit', 'Glob', 'Grep'],
    coder: ['Read', 'Write', 'Edit', 'Bash', 'Glob', 'Grep'],
    tester: ['Read', 'Write', 'Edit', 'Bash', 'Grep'],
    reviewer: ['Read', 'Glob', 'Grep'],
    researcher: ['Read', 'Glob', 'Grep', 'WebSearch'],
  };

  return AGENT_ROLES.map((agent) => {
    const tools = toolGroupMap[agent.role] || ['Read', 'Glob', 'Grep'];

    const content = `---
name: ${agent.role}
description: "${agent.description}"
tools: [${tools.join(', ')}]
---
# ${agent.icon} ${agent.title} Agent — ${vars.projectName}

> ${agent.description}

## Project Context
- **Framework**: ${vars.framework}
- **Language**: ${String(vars.languageLabel || vars.language)}
${vars.database ? `- **Database**: ${vars.database}` : ''}
${vars.testing ? `- **Testing**: ${vars.testing}` : ''}
- **Orchestration**: ${vars.orchestrationMode} (${vars.swarmTopology} topology)
- **Methodology**: ${vars.developmentMethodology === 'sparc' ? 'SPARC Protocol' : 'Standard'}

## Guardrails
${agent.guardrails.map((g) => `- ${g}`).join('\n')}
`;

    return {
      ideTarget: 'junie' as IDETarget,
      filename: `${agent.role}.md`,
      filePath: `.junie/agents/${agent.role}.md`,
      content,
    };
  });
}

// ── Factory: YAML Droid definitions ─────────────

function generateFactoryBlueprints(vars: TemplateVariables): GeneratedFile[] {
  const toolCategoryMap: Record<AgentRole, string[]> = {
    architect: ['read-only', 'edit'],
    coder: ['read-only', 'edit', 'execute'],
    tester: ['read-only', 'edit', 'execute'],
    reviewer: ['read-only'],
    researcher: ['read-only', 'web'],
  };

  return AGENT_ROLES.map((agent) => {
    const tools = toolCategoryMap[agent.role] || ['read-only'];

    const content = `# ${agent.title} Droid configuration
# Generated by Initra for ${vars.projectName}
name: ${agent.role}
description: "${agent.description}"
model: inherit
tools:
${tools.map((t) => `  - ${t}`).join('\n')}
instructions: |
  You are a ${agent.title} Droid for the ${vars.projectName} project.
  Framework: ${vars.framework} | Language: ${String(vars.languageLabel || vars.language)}
  ${vars.database ? `Database: ${vars.database}` : ''}
  
  Guardrails:
${agent.guardrails.map((g) => `  - ${g}`).join('\n')}
`;

    return {
      ideTarget: 'factory' as IDETarget,
      filename: `${agent.role}.yaml`,
      filePath: `.factory/droids/${agent.role}.yaml`,
      content,
    };
  });
}

// ── Windsurf: Markdown skill-like agent files ───

function generateWindsurfBlueprints(vars: TemplateVariables): GeneratedFile[] {
  // Windsurf doesn't have native subagent definitions like Cursor/Codex,
  // but supports skills and rules. Generate as specialized rule files.
  return AGENT_ROLES.map((agent) => {
    const content = `# ${agent.icon} ${agent.title} Agent — ${vars.projectName}

> ${agent.description}

## Project Context
- **Framework**: ${vars.framework}
- **Language**: ${String(vars.languageLabel || vars.language)}
${vars.database ? `- **Database**: ${vars.database}` : ''}

## Capabilities
${agent.capabilities.map((c) => `- ${c}`).join('\n')}

## Guardrails
${agent.guardrails.map((g) => `- ${g}`).join('\n')}
`;

    return {
      ideTarget: 'windsurf' as IDETarget,
      filename: `${agent.role}.md`,
      filePath: `.windsurf/skills/${agent.role}/SKILL.md`,
      content,
    };
  });
}

// ── GitHub Copilot: Agent.md definitions ────────

function generateCopilotBlueprints(vars: TemplateVariables): GeneratedFile[] {
  // VS Code Copilot supports .agent.md files in .github/agents/
  return AGENT_ROLES.map((agent) => {
    const content = `---
name: ${agent.role}
description: "${agent.description}"
---
# ${agent.icon} ${agent.title} Agent — ${vars.projectName}

> ${agent.description}

## Project Context
- **Framework**: ${vars.framework}
- **Language**: ${String(vars.languageLabel || vars.language)}
${vars.database ? `- **Database**: ${vars.database}` : ''}
${vars.testing ? `- **Testing**: ${vars.testing}` : ''}

## Capabilities
${agent.capabilities.map((c) => `- ${c}`).join('\n')}

## Guardrails
${agent.guardrails.map((g) => `- ${g}`).join('\n')}
`;

    return {
      ideTarget: 'copilot' as IDETarget,
      filename: `${agent.role}.agent.md`,
      filePath: `.github/agents/${agent.role}.agent.md`,
      content,
    };
  });
}
