// =============================================
// Initra — IDE Target Configurations
// =============================================

import { IDETargetConfig } from './types';

export const IDE_TARGETS: IDETargetConfig[] = [
  {
    slug: 'claude-code',
    name: 'Claude Code',
    icon: '🟣',
    configFilename: 'CLAUDE.md',
    configPath: 'CLAUDE.md',
    description: 'Claude Code agent context file. Supports persistent context via CLAUDE.md and extensible Agent Skills.',
    supportsMultiFile: false,
  },
  {
    slug: 'cursor',
    name: 'Cursor',
    icon: '⚡',
    configFilename: 'project-context.mdc',
    configPath: '.cursor/rules/project-context.mdc',
    description: 'Cursor AI rules, skills, and subagents. Supports persistent context, specialized workflows, and parallel task delegation.',
    supportsMultiFile: true,
  },
  {
    slug: 'windsurf',
    name: 'Windsurf',
    icon: '🌊',
    configFilename: 'project-context.md',
    configPath: '.windsurf/rules/project-context.md',
    description: 'Windsurf Cascade agent. Supports persistent context via Memories, Rules, and AGENTS.md.',
    supportsMultiFile: true,
  },
  {
    slug: 'gemini',
    name: 'Gemini',
    icon: '💎',
    configFilename: 'GEMINI.md',
    configPath: 'GEMINI.md',
    description: 'Gemini CLI/IDE agent instructions. Hierarchical loading from root.',
    supportsMultiFile: false,
  },
  {
    slug: 'copilot',
    name: 'GitHub Copilot',
    icon: '🐙',
    configFilename: 'copilot-instructions.md',
    configPath: '.github/copilot-instructions.md',
    description: 'GitHub Copilot agent instructions. Supports persistent context via Instructions, Custom Agents, and Agent Skills.',
    supportsMultiFile: false,
  },
  {
    slug: 'trae',
    name: 'Trae AI',
    icon: '🎋',
    configFilename: '.traerules',
    configPath: '.traerules',
    description: 'ByteDance Trae IDE rules. Supports adaptive project rules, global user rules, and on-demand Agent Skills.',
    supportsMultiFile: false,
  },
  {
    slug: 'aider',
    name: 'Aider',
    icon: '🤖',
    configFilename: '.aider.instructions.md',
    configPath: '.aider.instructions.md',
    description: 'Aider CLI agent instructions for persistent project context.',
    supportsMultiFile: false,
  },
  {
    slug: 'devin',
    name: 'Devin',
    icon: '📟',
    configFilename: 'instructions.md',
    configPath: '.devin/instructions.md',
    description: 'Autonomous Devin AI instruction set for complex engineering.',
    supportsMultiFile: false,
  },
  {
    slug: 'replit',
    name: 'Replit Agent',
    icon: '🌀',
    configFilename: '.replit',
    configPath: '.replit',
    description: 'Replit Agent specialized environment and build rules.',
    supportsMultiFile: false,
  },
  {
    slug: 'universal',
    name: 'Universal (AGENTS.md)',
    icon: '🌐',
    configFilename: 'AGENTS.md',
    configPath: 'AGENTS.md',
    description: 'Tool-agnostic open standard. Works across multiple AI coding agents.',
    supportsMultiFile: false,
  },
  {
    slug: 'antigravity',
    name: 'Google Antigravity',
    icon: '🚀',
    configFilename: 'project-rules.md',
    configPath: '.agents/rules/project-rules.md',
    description: 'Advanced agent orchestration with Rules, Workflows, and Skills.',
    supportsMultiFile: true,
  },
  {
    slug: 'codex',
    name: 'Codex',
    icon: '📜',
    configFilename: 'config.toml',
    configPath: '.codex/config.toml',
    description: 'Codex orchestration agent. Supports parallel subagents and CSV batch processing.',
    supportsMultiFile: true,
  },
  {
    slug: 'junie',
    name: 'Junie',
    icon: '🦊',
    configFilename: 'AGENTS.md',
    configPath: '.junie/AGENTS.md',
    description: 'Junie CLI and JetBrains agent. Supports Agent Skills, custom subagents, and AGENTS.md guidelines.',
    supportsMultiFile: true,
  },
  {
    slug: 'mistral-vibe',
    name: 'Mistral AI Vibe',
    icon: '🌪️',
    configFilename: 'config.toml',
    configPath: '.vibe/config.toml',
    description: 'Conversational CLI agent by Mistral AI. Supports subagents, skills, and interactive user questions.',
    supportsMultiFile: true,
  },
];

export function getIDETarget(slug: string): IDETargetConfig | undefined {
  return IDE_TARGETS.find((t) => t.slug === slug);
}
